application: gistyleguide
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: general.php

- url: /([^/]+\.php)
  script: \1

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /font
  static_dir: font

- url: /js
  static_dir: js